# Generated by Django 5.1.3 on 2024-11-09 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apple_shop", "0002_alter_product_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactData",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("address", models.CharField(default="Адреса нет", max_length=150, null=True, verbose_name="Адрес")),
                (
                    "phone_number",
                    models.CharField(
                        default="Телефонов для связи нет", max_length=50, null=True, verbose_name="Телефон"
                    ),
                ),
                ("email", models.CharField(default="Почты тоже нет", max_length=100, null=True, verbose_name="Почта")),
                (
                    "description",
                    models.TextField(
                        default="И гарантии нет \nКак и самих товаров \nЕсли что-то купили - покупайте еще \nИ друзьям предлагайте",
                        null=True,
                        verbose_name="Описание",
                    ),
                ),
            ],
            options={
                "verbose_name": "Контактные данные",
                "verbose_name_plural": "Контактные данные",
            },
        ),
    ]
