# Generated by Django 5.1.3 on 2024-11-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apple_shop", "0003_contactdata"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="apple_shop/categories/photo", verbose_name="Фото"
            ),
        ),
    ]
