# Generated by Django 5.1.3 on 2024-11-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("apple_shop", "0004_category_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="image",
        ),
        migrations.AddField(
            model_name="product",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="apple_shop/products/photo", verbose_name="Изображение товара"
            ),
        ),
    ]
